[package]
name = "pallet-collective"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/pallet-collective"
description = "Collective system: Members of a set of account IDs can make their collective feelings known through dispatched calls from one of two specialized origins."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tet-core = { version = "2.0.2", default-features = false, path = "../../primitives/core" }
tetcore-std = { version = "2.0.2", default-features = false, path = "../../primitives/std" }
tet-io = { version = "2.0.2", default-features = false, path = "../../primitives/io" }
tp-runtime = { version = "2.0.2", default-features = false, path = "../../primitives/runtime" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }

[dev-dependencies]
hex-literal = "0.3.1"
pallet-balances = { version = "2.0.0", path = "../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"tet-core/std",
	"tetcore-std/std",
	"serde",
	"tet-io/std",
	"frame-support/std",
	"tp-runtime/std",
	"frame-system/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"tp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
