[package]
name = "tc-arithmetic-fuzzer"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Fuzzer for fixed point arithmetic primitives."
documentation = "https://docs.rs/tc-arithmetic-fuzzer"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-arithmetic = { version = "2.0.0", path = ".." }
honggfuzz = "0.5.49"
primitive-types = "0.9.0"
num-bigint = "0.2"
num-traits = "0.2"

[[bin]]
name = "biguint"
path = "src/biguint.rs"

[[bin]]
name = "normalize"
path = "src/normalize.rs"

[[bin]]
name = "per_thing_rational"
path = "src/per_thing_rational.rs"

[[bin]]
name = "multiply_by_rational"
path = "src/multiply_by_rational.rs"

[[bin]]
name = "fixed_point"
path = "src/fixed_point.rs"
