[package]
name = "arithmetic-fuzzer"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "Fuzzer for fixed point arithmetic primitives."
documentation = "https://docs.rs/arithmetic-fuzzer"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
arithmetic = { version = "2.0.2", path = ".." }
honggfuzz = "0.5.49"
tetsy-primitive-types = "0.9.1"
num-bigint = "0.2"
num-traits = "0.2"

[[bin]]
name = "biguint"
path = "src/biguint.rs"

[[bin]]
name = "normalize"
path = "src/normalize.rs"

[[bin]]
name = "per_thing_rational"
path = "src/per_thing_rational.rs"

[[bin]]
name = "multiply_by_rational"
path = "src/multiply_by_rational.rs"

[[bin]]
name = "fixed_point"
path = "src/fixed_point.rs"
