[package]
name = "pallet-aura"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME AURA consensus pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-application-crypto = { version = "2.0.0", default-features = false, path = "../../primitives/application-crypto" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-inherents = { version = "2.0.0", default-features = false, path = "../../primitives/inherents" }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
serde = { version = "1.0.101", optional = true }
pallet-session = { version = "2.0.0", default-features = false, path = "../session" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
tc-consensus-aura = { version = "0.8.0", path = "../../primitives/consensus/aura", default-features = false }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
tc-timestamp = { version = "2.0.0", default-features = false, path = "../../primitives/timestamp" }
pallet-timestamp = { version = "2.0.0", default-features = false, path = "../timestamp" }


[dev-dependencies]
tc-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tc-io ={ version = "2.0.0", path = "../../primitives/io" }
lazy_static = "1.4.0"
parking_lot = "0.11.1"

[features]
default = ["std"]
std = [
	"tc-application-crypto/std",
	"codec/std",
	"tc-inherents/std",
	"tc-std/std",
	"serde",
	"tc-runtime/std",
	"frame-support/std",
	"tc-consensus-aura/std",
	"frame-system/std",
	"tc-timestamp/std",
	"pallet-timestamp/std",
]
