[package]
name = "pallet-timestamp"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME Timestamp Module"
documentation = "https://docs.rs/pallet-timestamp"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tc-io = { version = "2.0.0", default-features = false, path = "../../primitives/io", optional = true }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tc-inherents = { version = "2.0.0", default-features = false, path = "../../primitives/inherents" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
tc-timestamp = { version = "2.0.0", default-features = false, path = "../../primitives/timestamp" }
impl-trait-for-tuples = "0.2.0"

[dev-dependencies]
tc-io ={ version = "2.0.0", path = "../../primitives/io" }
tc-core = { version = "2.0.0", path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"tc-inherents/std",
	"codec/std",
	"tc-std/std",
	"tc-runtime/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"serde",
	"frame-system/std",
	"tc-timestamp/std"
]
runtime-benchmarks = ["frame-benchmarking", "tc-io"]
