[package]
name = "tp-election-providers"
version = "2.0.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/babe"
description = "Primitive election providers"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.0.2", default-features = false, path = "../std" }
arithmetic = { version = "2.0.2", default-features = false, path = "../arithmetic" }
tp-npos-elections = { version = "2.0.2", default-features = false, path = "../npos-elections" }

[dev-dependencies]
tp-npos-elections = { version = "2.0.2", path = "../npos-elections" }
tp-runtime = { version = "2.0.2", path = "../runtime" }

[features]
default = ["std"]
runtime-benchmarks = []
std = [
	"codec/std",
	"tetcore-std/std",
	"tp-npos-elections/std",
	"arithmetic/std",
]
