[package]
name = "tc-election-providers"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Primitive election providers"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-std = { version = "2.0.1", default-features = false, path = "../std" }
tc-arithmetic = { version = "2.0.1", default-features = false, path = "../arithmetic" }
tc-npos-elections = { version = "2.0.1", default-features = false, path = "../npos-elections" }

[dev-dependencies]
tc-npos-elections = { version = "2.0.1", path = "../npos-elections" }
tc-runtime = { version = "2.0.1", path = "../runtime" }

[features]
default = ["std"]
runtime-benchmarks = []
std = [
	"codec/std",
	"tc-std/std",
	"tc-npos-elections/std",
	"tc-arithmetic/std",
]
