[package]
name = "tc-runtime-test"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
publish = false
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tc-authority-discovery"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-allocator = { version = "2.0.2", default-features = false, path = "../../../primitives/allocator" }
tet-core = { version = "2.0.2", default-features = false, path = "../../../primitives/core" }
tet-io = { version = "2.0.2", default-features = false, path = "../../../primitives/io" }
tp-runtime = { version = "2.0.2", default-features = false, path = "../../../primitives/runtime" }
tp-sandbox = { version = "0.8.2", default-features = false, path = "../../../primitives/sandbox" }
tetcore-std = { version = "2.0.2", default-features = false, path = "../../../primitives/std" }
tp-tasks = { version = "2.0.1", default-features = false, path = "../../../primitives/tasks" }

[build-dependencies]
wasm-builder = { version = "3.0.0", path = "../../../utils/wasm-builder" }

[features]
default = [ "std" ]
std = [
	"tp-allocator/std",
	"tet-core/std",
	"tet-io/std",
	"tp-runtime/std",
	"tp-sandbox/std",
	"tetcore-std/std",
 	"tp-tasks/std",
]
