[package]
name = "sc-runtime-test"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
publish = false
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-allocator = { version = "2.0.0", default-features = false, path = "../../../primitives/allocator" }
tc-core = { version = "2.0.0", default-features = false, path = "../../../primitives/core" }
tc-io = { version = "2.0.0", default-features = false, path = "../../../primitives/io" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
tc-sandbox = { version = "0.8.0", default-features = false, path = "../../../primitives/sandbox" }
tc-std = { version = "2.0.0", default-features = false, path = "../../../primitives/std" }
tc-tasks = { version = "2.0.0", default-features = false, path = "../../../primitives/tasks" }

[build-dependencies]
tetcore-wasm-builder = { version = "3.0.0", path = "../../../utils/wasm-builder" }

[features]
default = [ "std" ]
std = [
	"tc-allocator/std",
	"tc-core/std",
	"tc-io/std",
	"tc-runtime/std",
	"tc-sandbox/std",
	"tc-std/std",
 	"tc-tasks/std",
]
