[package]
name = "node-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-system = { version = "2.0.0", default-features = false, path = "../../../frame/system" }
tc-application-crypto = { version = "2.0.0", default-features = false, path = "../../../primitives/application-crypto" }
tc-core = { version = "2.0.0", default-features = false, path = "../../../primitives/core" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }

[dev-dependencies]
tc-serializer = { version = "2.0.0", path = "../../../primitives/serializer" }
pretty_assertions = "0.6.1"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-system/std",
	"tc-application-crypto/std",
	"tc-core/std",
	"tc-runtime/std",
]
