[package]
name = "tetcore-test-utils-test-crate"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetcore Testing Utilities Test Crate"
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
# publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
tokio = { version = "0.2.13", features = ["macros"] }
test-utils = { version = "2.1.2", path = "..", package = "tetcore-test-utils" }
tc-service = { version = "2.1.2", path = "../../client/service" }
