[package]
name = "pallet-elections-phragmen"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME pallet based on seq-Phragmén election method."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tp-npos-elections = { version = "2.0.0", default-features = false, path = "../../primitives/npos-elections" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
tp-io = { version = "2.0.0", path = "../../primitives/io" }
hex-literal = "0.3.1"
pallet-balances = { version = "2.0.0", path = "../balances" }
tp-core = { version = "2.0.0", path = "../../primitives/core" }
tetcore-test-utils = { version = "2.0.0", path = "../../test-utils" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"frame-support/std",
	"tp-runtime/std",
	"tp-npos-elections/std",
	"frame-system/std",
	"tetcore-std/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
