[package]
name = "tp-api-proc-macro"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "Tetcore Macros for declaring and implementing runtime apis."
documentation = "https://docs.rs/tp-api-proc-macro"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
syn = { version = "1.0.58", features = ["full", "fold", "extra-traits", "visit"] }
proc-macro2 = "1.0.6"
blake2-rfc = { version = "0.2.18", default-features = false }
proc-macro-crate = "0.1.4"

# Required for the doc tests
[features]
default = [ "std" ]
std = []
