[package]
name = "tetcore-test-runtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-application-crypto = { version = "2.0.0", default-features = false, path = "../../primitives/application-crypto" }
tc-consensus-aura = { version = "0.8.0", default-features = false, path = "../../primitives/consensus/aura" }
tc-consensus-babe = { version = "0.8.0", default-features = false, path = "../../primitives/consensus/babe" }
tc-block-builder = { version = "2.0.0", default-features = false, path = "../../primitives/block-builder" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-executive = { version = "2.0.0", default-features = false, path = "../../frame/executive" }
tc-inherents = { version = "2.0.0", default-features = false, path = "../../primitives/inherents" }
tc-keyring = { version = "2.0.0", optional = true, path = "../../primitives/keyring" }
memory-db = { version = "0.26.0", default-features = false }
tc-offchain = { path = "../../primitives/offchain", default-features = false, version = "2.0.0"}
tc-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tc-runtime-interface = { path = "../../primitives/runtime-interface", default-features = false, version = "2.0.0"}
tc-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
frame-support = { version = "2.0.0", default-features = false, path = "../../frame/support" }
tc-version = { version = "2.0.0", default-features = false, path = "../../primitives/version" }
tc-session = { version = "2.0.0", default-features = false, path = "../../primitives/session" }
tc-api = { version = "2.0.0", default-features = false, path = "../../primitives/api" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
pallet-babe = { version = "2.0.0", default-features = false, path = "../../frame/babe" }
frame-system = { version = "2.0.0", default-features = false, path = "../../frame/system" }
frame-system-rpc-runtime-api = { version = "2.0.0", default-features = false, path = "../../frame/system/rpc/runtime-api" }
pallet-timestamp = { version = "2.0.0", default-features = false, path = "../../frame/timestamp" }
tc-finality-grandpa = { version = "2.0.0", default-features = false, path = "../../primitives/finality-grandpa" }
tc-trie = { version = "2.0.0", default-features = false, path = "../../primitives/trie" }
tc-transaction-pool = { version = "2.0.0", default-features = false, path = "../../primitives/transaction-pool" }
trie-db = { version = "0.22.2", default-features = false }
tetsy-util-mem = { version = "0.9.0", default-features = false, features = ["primitive-types"] }
sc-service = { version = "0.8.0", default-features = false, optional = true, features = ["test-helpers"], path = "../../client/service" }
tc-state-machine = { version = "0.8.0", default-features = false, path = "../../primitives/state-machine" }
tc-externalities = { version = "0.8.0", default-features = false, path = "../../primitives/externalities" }

# 3rd party
cfg-if = "0.1.10"
log = { version = "0.4.8", optional = true }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

[dev-dependencies]
sc-block-builder = { version = "0.8.0", path = "../../client/block-builder" }
sc-executor = { version = "0.8.0", path = "../../client/executor" }
tetcore-test-runtime-client = { version = "2.0.0", path = "./client" }

[build-dependencies]
tetcore-wasm-builder = { version = "3.0.0", path = "../../utils/wasm-builder" }

[features]
default = [
	"std",
]
std = [
	"tc-application-crypto/std",
	"tc-consensus-aura/std",
	"tc-consensus-babe/std",
	"tc-block-builder/std",
	"codec/std",
	"frame-executive/std",
	"tc-inherents/std",
	"tc-keyring",
	"log",
	"memory-db/std",
	"tc-offchain/std",
	"tc-core/std",
	"tc-core/std",
	"tc-std/std",
	"tc-runtime-interface/std",
	"tc-io/std",
	"frame-support/std",
	"tc-version/std",
	"serde",
	"tc-session/std",
	"tc-api/std",
	"tc-runtime/std",
	"tc-externalities/std",
	"tc-state-machine/std",
	"pallet-babe/std",
	"frame-system-rpc-runtime-api/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sc-service",
	"tc-finality-grandpa/std",
	"tc-trie/std",
	"tc-transaction-pool/std",
	"trie-db/std",
]
