[package]
name = "noble-contracts-rpc"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "Node-specific RPC methods for interaction with contracts."
readme = "README.md"
# publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
tetsy-jsonrpc-core = "15.1.0"
tetsy-jsonrpc-core-client = "15.1.0"
tetsy-jsonrpc-derive = "15.1.0"
tp-blockchain = { version = "2.1.2", path = "../../../primitives/blockchain" }
tet-core = { version = "2.1.2", path = "../../../primitives/core" }
tp-rpc = { version = "2.1.2", path = "../../../primitives/rpc" }
serde = { version = "1.0.101", features = ["derive"] }
tp-runtime = { version = "2.1.2", path = "../../../primitives/runtime" }
tp-api = { version = "2.1.2", path = "../../../primitives/api" }
noble-contracts-primitives = { version = "2.1.2", path = "../common" }
noble-contracts-rpc-runtime-api = { version = "2.1.2", path = "./runtime-api" }

[dev-dependencies]
serde_json = "1.0.41"
