environment:
  matrix:
    - FEATURES: ""

platform:
  - x86_64-pc-windows-msvc

# avoid running tests twice
branches:
  only:
    - master

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %PLATFORM%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV
  - rustup install nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly

build_script:
  - cargo check --workspace --exclude tp-npos-elections-fuzzer --exclude arithmetic-fuzzer --exclude noble-staking-fuzz --tests
  - cargo build --workspace --exclude tp-npos-elections-fuzzer --exclude arithmetic-fuzzer --exclude noble-staking-fuzz

test_script:
  - cargo test --workspace --exclude tp-npos-elections-fuzzer --exclude arithmetic-fuzzer --exclude noble-staking-fuzz
