[package]
name = "debug-derive"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "Macros to derive runtime debug implementation."
documentation = "https://docs.rs/debug-derive"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
quote = "1.0.3"
syn = "1.0.58"
proc-macro2 = "1.0"

[features]
std = []

[dev-dependencies]
