[package]
name = "tetcore-frame-rpc-system"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME's system exposed over Tetcore RPC"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-client-api = { version = "2.0.0", path = "../../../../client/api" }
codec = { package = "tetsy-scale-codec", version = "2.0.0" }
futures = { version = "0.3.4", features = ["compat"] }
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
log = "0.4.8"
serde = { version = "1.0.101", features = ["derive"] }
tc-runtime = { version = "2.0.0", path = "../../../../primitives/runtime" }
tc-api = { version = "2.0.0", path = "../../../../primitives/api" }
frame-system-rpc-runtime-api = { version = "2.0.0", path = "../../../../frame/system/rpc/runtime-api" }
tc-core = { version = "2.0.0", path = "../../../../primitives/core" }
tc-blockchain = { version = "2.0.0", path = "../../../../primitives/blockchain" }
tc-transaction-pool = { version = "2.0.0", path = "../../../../primitives/transaction-pool" }
tc-block-builder = { version = "2.0.0", path = "../../../../primitives/block-builder" }
sc-rpc-api = { version = "0.8.0", path = "../../../../client/rpc-api" }

[dev-dependencies]
tetcore-test-runtime-client = { version = "2.0.0", path = "../../../../test-utils/runtime/client" }
tc-tracing = { version = "2.0.0", path = "../../../../primitives/tracing" }
sc-transaction-pool = { version = "2.0.0", path = "../../../../client/transaction-pool" }
