[package]
name = "pallet-session-benchmarking"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME sessions pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tetcore-std = { version = "2.0.2", default-features = false, path = "../../../primitives/std" }
tp-session = { version = "2.0.2", default-features = false, path = "../../../primitives/session" }
tp-runtime = { version = "2.0.2", default-features = false, path = "../../../primitives/runtime" }
frame-system = { version = "2.0.0", default-features = false, path = "../../system" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../../benchmarking" }
frame-support = { version = "2.0.0", default-features = false, path = "../../support" }
pallet-staking = { version = "2.0.0", default-features = false, features = ["runtime-benchmarks"], path = "../../staking" }
pallet-session = { version = "2.0.0", default-features = false, path = "../../session" }
rand = { version = "0.7.2", default-features = false }

[dev-dependencies]
serde = { version = "1.0.101" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", features = ["derive"] }
tet-core = { version = "2.0.2", path = "../../../primitives/core" }
pallet-staking-reward-curve = { version = "2.0.0", path = "../../staking/reward-curve" }
tet-io ={ version = "2.0.2", path = "../../../primitives/io" }
pallet-timestamp = { version = "2.0.0", path = "../../timestamp" }
pallet-balances = { version = "2.0.0", path = "../../balances" }

[features]
default = ["std"]
std = [
	"tetcore-std/std",
	"tp-session/std",
	"tp-runtime/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"pallet-staking/std",
	"pallet-session/std",
]
