[package]
name = "fabric-executive"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/executive"
description = "FABRIC executives engine"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
fabric-support = { version = "2.0.0", default-features = false, path = "../support" }
fabric-system = { version = "2.0.0", default-features = false, path = "../system" }
serde = { version = "1.0.101", optional = true }
tp-runtime = { version = "2.0.2", default-features = false, path = "../../primitives/runtime" }
tetcore-tracing = { version = "2.0.2", default-features = false, path = "../../primitives/tracing" }
tetcore-std = { version = "2.0.2", default-features = false, path = "../../primitives/std" }
tet-io = { version = "2.0.2", default-features = false, path = "../../primitives/io" }
tet-core = { version = "2.0.2", default-features = false, path = "../../primitives/core" }

[dev-dependencies]
hex-literal = "0.3.1"
tet-core = { version = "2.0.2", path = "../../primitives/core" }
tet-io ={ version = "2.0.2", path = "../../primitives/io" }
noble-indices = { version = "2.0.0", path = "../indices" }
noble-balances = { version = "2.0.1", path = "../balances" }
noble-transaction-payment = { version = "2.0.0", path = "../transaction-payment" }
tp-version = { version = "2.0.2", path = "../../primitives/version" }

[features]
default = ["std"]
with-tracing = [
	"tetcore-tracing/with-tracing"
]
std = [
	"codec/std",
	"fabric-support/std",
	"fabric-system/std",
	"serde",
	"tet-core/std",
	"tp-runtime/std",
	"tetcore-tracing/std",
	"tetcore-std/std",
]
