[package]
name = "tp-runtime-interface-test-wasm-deprecated"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
build = "build.rs"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-runtime-interface = { version = "2.0.2", default-features = false, path = "../" }
tetcore-std = { version = "2.0.2", default-features = false, path = "../../std" }
tet-io = { version = "2.0.2", default-features = false, path = "../../io" }
tet-core = { version = "2.0.2", default-features = false, path = "../../core" }

[build-dependencies]
wasm-builder = { version = "3.0.0", path = "../../../utils/wasm-builder" }

[features]
default = [ "std" ]
std = [ "tp-runtime-interface/std", "tetcore-std/std", "tet-core/std", "tet-io/std" ]
