[package]
name = "tc-runtime-test"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
publish = false
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-allocator = { version = "2.0.0", default-features = false, path = "../../../primitives/allocator" }
tp-core = { version = "2.0.0", default-features = false, path = "../../../primitives/core" }
tp-io = { version = "2.0.0", default-features = false, path = "../../../primitives/io" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
tp-sandbox = { version = "0.8.0", default-features = false, path = "../../../primitives/sandbox" }
tp-std = { version = "2.0.0", default-features = false, path = "../../../primitives/std" }
tp-tasks = { version = "2.0.0", default-features = false, path = "../../../primitives/tasks" }

[build-dependencies]
tetcore-wasm-builder = { version = "3.0.0", path = "../../../utils/wasm-builder" }

[features]
default = [ "std" ]
std = [
	"tp-allocator/std",
	"tp-core/std",
	"tp-io/std",
	"tp-runtime/std",
	"tp-sandbox/std",
	"tp-std/std",
 	"tp-tasks/std",
]
