[package]
name = "pallet-staking"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/staking"
description = "FRAME pallet staking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tp-npos-elections = { version = "2.0.0", default-features = false, path = "../../primitives/npos-elections" }
tp-io ={ version = "2.0.0", default-features = false, path = "../../primitives/io" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tp-staking = { version = "2.0.0", default-features = false, path = "../../primitives/staking" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
pallet-session = { version = "2.0.0", default-features = false, features = ["historical"], path = "../session" }
pallet-authorship = { version = "2.0.0", default-features = false, path = "../authorship" }
tp-application-crypto = { version = "2.0.0", default-features = false, path = "../../primitives/application-crypto" }

# Optional imports for benchmarking
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
tet-core = { version = "2.0.0", path = "../../primitives/core" }
tetcore-storage = { version = "2.0.0", path = "../../primitives/storage" }
tetcore-tracing = { version = "2.0.0", path = "../../primitives/tracing" }
pallet-balances = { version = "2.0.0", path = "../balances" }
pallet-timestamp = { version = "2.0.0", path = "../timestamp" }
pallet-staking-reward-curve = { version = "2.0.0",  path = "../staking/reward-curve" }
tetcore-test-utils = { version = "2.0.0", path = "../../test-utils" }
frame-benchmarking = { version = "2.0.0", path = "../benchmarking" }
rand_chacha = { version = "0.2" }
parking_lot = "0.11.1"
hex = "0.4"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tetcore-std/std",
	"tp-npos-elections/std",
	"tp-io/std",
	"frame-support/std",
	"tp-runtime/std",
	"tp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"tp-application-crypto/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand_chacha",
]
