[package]
name = "frame-system"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/frame-system"
description = "FRAME system module"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tet-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tp-io = { version = "2.0.0", path = "../../primitives/io", default-features = false }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tp-version = { version = "2.0.0", default-features = false, path = "../../primitives/version" }
frame-support = { version = "2.0.1", default-features = false, path = "../support" }
impl-trait-for-tuples = "0.2.0"

[dev-dependencies]
criterion = "0.3.3"
externalities = { version = "0.8.0", path = "../../primitives/externalities" }
tetcore-test-runtime-client = { version = "2.0.0", path = "../../test-utils/runtime/client" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tet-core/std",
	"tetcore-std/std",
	"tp-io/std",
	"frame-support/std",
	"tp-runtime/std",
	"tp-version/std",
]
runtime-benchmarks = [
	"tp-runtime/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
]

[[bench]]
name = "bench"
harness = false
