[package]
name = "tc-consensus-manual-seal"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Manual sealing engine for Tetcore"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tc-consensus-manual-seal"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
derive_more = "0.99.2"
futures = "0.3.9"
tetsy-jsonrpc-core = "15.1.0"
tetsy-jsonrpc-core-client = "15.1.0"
tetsy-jsonrpc-derive = "15.1.0"
log = "0.4.8"
parking_lot = "0.11.1"
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
serde = { version = "1.0", features=["derive"] }
assert_matches = "1.3.0"

tc-client-api = { version = "2.1.2", path = "../../api" }
tc-consensus-babe = { version ="2.1.2", path = "../../consensus/babe" }
tc-consensus-epochs = { version ="2.1.2", path = "../../consensus/epochs" }
tp-consensus-babe = { version ="2.1.2", path = "../../../primitives/consensus/babe" }

tc-transaction-pool = { version ="2.1.2", path = "../../transaction-pool" }
tp-blockchain = { version ="2.1.2", path = "../../../primitives/blockchain" }
tp-consensus = { version ="2.1.2", path = "../../../primitives/consensus/common" }
tp-consensus-slots = { version ="2.1.2", path = "../../../primitives/consensus/slots" }
tp-inherents = { version ="2.1.2", path = "../../../primitives/inherents" }
tp-runtime = { version ="2.1.2", path = "../../../primitives/runtime" }
tet-core = { version ="2.1.2", path = "../../../primitives/core" }
tp-keystore = { version ="2.1.2", path = "../../../primitives/keystore" }
tp-keyring = { version ="2.1.2", path = "../../../primitives/keyring" }
tp-api = { version ="2.1.2", path = "../../../primitives/api" }
tp-transaction-pool = { version ="2.1.2", path = "../../../primitives/transaction-pool" }
tp-timestamp = { version ="2.1.2", path = "../../../primitives/timestamp" }

prometheus-endpoint = { version ="2.1.2", package = "prometheus-endpoint", path = "../../../utils/prometheus" }

[dev-dependencies]
tokio = { version = "0.2", features = ["rt-core", "macros"] }
tc-basic-authorship = { version ="2.1.2", path = "../../basic-authorship" }
tetcore-test-runtime-client = { path = "../../../test-utils/runtime/client" }
tetcore-test-runtime-transaction-pool = { path = "../../../test-utils/runtime/transaction-pool" }
tempfile = "3.1.0"
