[package]
name = "tetcore-browser-utils"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Utilities for creating a browser light-client."
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tetcore-browser-utils"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = { version = "0.3", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
log = "0.4.8"
tetsy-libp2p-wasm-ext = { version = "0.27.1", features = ["websocket"] }
console_error_panic_hook = "0.1.6"
js-sys = "0.3.50"
wasm-bindgen = "0.2.73"
wasm-bindgen-futures = "0.4.23"
tetsy-kvdb-web = "0.9.1"
tetcore-database = { version = "2.1.2", path = "../../primitives/database" }
tc-informant = { version = "2.1.2", path = "../../client/informant" }
tc-service = { version = "2.1.2", path = "../../client/service", default-features = false }
tc-network = { version = "2.1.2", path = "../../client/network" }
tc-chain-spec = { version = "2.1.2", path = "../../client/chain-spec" }
tc-telemetry = { version = "2.1.2", path = "../../client/telemetry" }
tc-tracing = { version = "2.1.2", path = "../../client/tracing" }

# Imported just for the `wasm-bindgen` feature
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.7", features = ["wasm-bindgen"] }
futures-timer = { version = "3.0.1", features = ["wasm-bindgen"]}
chrono = { version = "0.4", features = ["wasmbind"] }
