[package]
name = "wasm-builder"
version = "3.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetcore utility for building WASM binaries"
edition = "2018"
readme = "README.md"
repository = "https://github.com/tetcoin/tetcore/"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
build-helper = "0.1.1"
cargo_metadata = "0.12.0"
tempfile = "3.1.0"
toml = "0.5.4"
walkdir = "2.3.1"
tetsy-wasm-gc-api = "0.1.11"
atty = "0.2.13"
ansi_term = "0.12.1"
