[package]
name = "tp-runtime-interface"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Tetcore runtime interface"
documentation = "https://docs.rs/tp-runtime-interface/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-wasm-interface = { version = "2.0.0", path = "../wasm-interface", default-features = false }
tp-std = { version = "2.0.0", default-features = false, path = "../std" }
tp-tracing = { version = "2.0.0", default-features = false, path = "../tracing" }
tp-runtime-interface-proc-macro = { version = "2.0.0", path = "proc-macro" }
tp-externalities = { version = "0.8.0", optional = true, path = "../externalities" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
static_assertions = "1.0.0"
primitive-types = { version = "0.9.0", default-features = false }
tp-storage = { version = "2.0.0", default-features = false, path = "../storage" }
impl-trait-for-tuples = "0.2.0"

[dev-dependencies]
tp-runtime-interface-test-wasm = { version = "2.0.0", path = "test-wasm" }
tp-state-machine = { version = "0.8.0", path = "../state-machine" }
tp-core = { version = "2.0.0", path = "../core" }
tp-io = { version = "2.0.0", path = "../io" }
rustversion = "1.0.0"
trybuild = "1.0.38"

[features]
default = [ "std" ]
std = [
	"tp-wasm-interface/std",
	"tp-std/std",
	"tp-tracing/std",
	"codec/std",
	"tp-externalities",
	"primitive-types/std",
]

# ATTENTION
#
# Only use when you know what you are doing.
#
# Disables static assertions in `impls.rs` that checks the word size. To prevent any footgun, the
# check is changed into a runtime check.
disable_target_static_assertions = []
