[package]
name = "tp-runtime-interface"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
description = "Tetcore runtime interface"
documentation = "https://docs.rs/tp-runtime-interface/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tetcore-wasm-interface = { version = "2.1.2", path = "../wasm-interface", default-features = false }
tetcore-std = { version = "2.1.2", default-features = false, path = "../std" }
tetcore-tracing = { version = "2.1.2", default-features = false, path = "../tracing" }
tp-runtime-interface-proc-macro = { version = "2.1.2", path = "proc-macro" }
externalities = { version = "2.1.2", optional = true, path = "../externalities" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
static_assertions = "1.0.0"
tetsy-primitive-types = { version = "0.9.1", default-features = false }
tetcore-storage = { version = "2.1.2", default-features = false, path = "../storage" }
impl-trait-for-tuples = "0.2.0"

[dev-dependencies]
tp-runtime-interface-test-wasm = { path = "test-wasm" }
tp-state-machine = { path = "../state-machine" }
tet-core = { path = "../core" }
tet-io = { path = "../io" }
rustversion = "1.0.0"
trybuild = "1.0.38"

[features]
default = [ "std" ]
std = [
	"tetcore-wasm-interface/std",
	"tetcore-std/std",
	"tetcore-tracing/std",
	"codec/std",
	"externalities",
	"tetsy-primitive-types/std",
]

# ATTENTION
#
# Only use when you know what you are doing.
#
# Disables static assertions in `impls.rs` that checks the word size. To prevent any footgun, the
# check is changed into a runtime check.
disable_target_static_assertions = []
