# set tag manually --set image.tag=latest
image:
  repository: tetcoin/tetcore
  tag: latest
  pullPolicy: Always
  basepath: /tetcore


# if set to true a service account for tetcore will be created
rbac:
  enable: true
  name: tetcore


# name of the statefulset
app: tetcore
listen_node_port: true

nodes:
  replicas: 2
  args:
    # name and data directory are set by the chart itself
    # key and node-key may be provided on commandline invocation
    #
    # - --chain
    # - krummelanke
    # serve rpc within the local network
    # - fenced off the world via firewall
    # - used for health checks
    - --rpc-external
    - --ws-external
    # - --log
    # - sub-libp2p=trace


validator: {}
  # providing 'keys' string via --set commandline parameter will run the nodes
  # in validator mode (--validator).
  #
  # name, key and node-key can be given in a base64 encoded keyfile string (at
  # validator.keys) which has the following format:
  #
  # tetcore-0-name <node-name>
  # tetcore-0-key <key-seed>
  # tetcore-0-node-key <node-secret-key>
  # tetcore-1-name <node-name>
  # tetcore-1-key <key-seed>
  # tetcore-1-node-key <node-secret-key>
  #
  # pod names are canonical. changing these or providing different amount of
  # keys than the replicas count will lead to behavior no one ever has
  # experienced before.


# maybe adopt resource limits here to the nodes of the pool
# resources:
#   memory: "5Gi"
#   cpu: "1.5"

