[package]
name = "tc-io"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "I/O for Tetcore runtimes"
documentation = "https://docs.rs/tc-io"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
tc-core = { version = "2.0.0", default-features = false, path = "../core" }
tc-keystore = { version = "0.8.0", default-features = false, optional = true, path = "../keystore" }
tc-std = { version = "2.0.0", default-features = false, path = "../std" }
libsecp256k1 = { version = "0.3.4", optional = true }
tc-state-machine = { version = "0.8.0", optional = true, path = "../state-machine" }
tc-wasm-interface = { version = "2.0.0", path = "../wasm-interface", default-features = false }
tc-runtime-interface = { version = "2.0.0", default-features = false, path = "../runtime-interface" }
tc-trie = { version = "2.0.0", optional = true, path = "../trie" }
tc-externalities = { version = "0.8.0", optional = true, path = "../externalities" }
tc-tracing = { version = "2.0.0", default-features = false, path = "../tracing" }
log = { version = "0.4.8", optional = true }
futures = { version = "0.3.1", features = ["thread-pool"], optional = true }
parking_lot = { version = "0.11.1", optional = true }
tracing = { version = "0.1.22", default-features = false }
tracing-core = { version = "0.1.17", default-features = false}

[features]
default = ["std"]
std = [
	"tc-core/std",
	"tc-keystore",
	"codec/std",
	"tc-std/std",
	"hash-db/std",
	"tc-trie",
	"tc-state-machine",
	"libsecp256k1",
	"tc-runtime-interface/std",
	"tc-externalities",
	"tc-wasm-interface/std",
	"tc-tracing/std",
	"tracing/std",
	"tracing-core/std",
	"log",
	"futures",
	"parking_lot",
]

with-tracing = [
	"tc-tracing/with-tracing"
]

# These two features are used for `no_std` builds for the environments which already provides
# `#[panic_handler]`, `#[alloc_error_handler]` and `#[global_allocator]`.
#
# For the regular wasm runtime builds those are not used.
disable_panic_handler = []
disable_oom = []
disable_allocator = []
