[package]
name = "tet-io"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
description = "I/O for Tetcore runtimes"
documentation = "https://docs.rs/tet-io"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
tetsy-hash-db = { version = "0.15.2", default-features = false }
tet-core = { version = "2.0.1", default-features = false, path = "../core" }
tp-keystore = { version = "0.8.0", default-features = false, optional = true, path = "../keystore" }
tetcore-std = { version = "2.0.1", default-features = false, path = "../std" }
libsecp256k1 = { version = "0.3.4", optional = true }
tp-state-machine = { version = "0.8.1", optional = true, path = "../state-machine" }
tetcore-wasm-interface = { version = "2.0.1", path = "../wasm-interface", default-features = false }
tp-runtime-interface = { version = "2.0.1", default-features = false, path = "../runtime-interface" }
tp-trie = { version = "2.0.1", optional = true, path = "../trie" }
externalities = { version = "0.8.1", optional = true, path = "../externalities" }
tetcore-tracing = { version = "2.0.1", default-features = false, path = "../tracing" }
log = { version = "0.4.8", optional = true }
futures = { version = "0.3.1", features = ["thread-pool"], optional = true }
parking_lot = { version = "0.11.1", optional = true }
tracing = { version = "0.1.22", default-features = false }
tracing-core = { version = "0.1.17", default-features = false}

[features]
default = ["std"]
std = [
	"tet-core/std",
	"tp-keystore",
	"codec/std",
	"tetcore-std/std",
	"tetsy-hash-db/std",
	"tp-trie",
	"tp-state-machine",
	"libsecp256k1",
	"tp-runtime-interface/std",
	"externalities",
	"tetcore-wasm-interface/std",
	"tetcore-tracing/std",
	"tracing/std",
	"tracing-core/std",
	"log",
	"futures",
	"parking_lot",
]

with-tracing = [
	"tetcore-tracing/with-tracing"
]

# These two features are used for `no_std` builds for the environments which already provides
# `#[panic_handler]`, `#[alloc_error_handler]` and `#[global_allocator]`.
#
# For the regular wasm runtime builds those are not used.
disable_panic_handler = []
disable_oom = []
disable_allocator = []
