[package]
name = "tc-consensus-pow"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "PoW consensus algorithm for tetcore"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tc-consensus-pow"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", features = ["derive"] }
tet-core = { version = "2.1.2", path = "../../../primitives/core" }
tp-blockchain = { version = "2.1.2", path = "../../../primitives/blockchain" }
tp-runtime = { version = "2.1.2", path = "../../../primitives/runtime" }
tp-api = { version = "2.1.2", path = "../../../primitives/api" }
tc-client-api = { version = "2.1.2", path = "../../api" }
tp-block-builder = { version = "2.1.2", path = "../../../primitives/block-builder" }
tp-inherents = { version = "2.1.2", path = "../../../primitives/inherents" }
tp-consensus-pow = { version = "2.1.2", path = "../../../primitives/consensus/pow" }
tp-consensus = { version = "2.1.2", path = "../../../primitives/consensus/common" }
log = "0.4.8"
futures = { version = "0.3.1", features = ["compat"] }
futures-timer = "3.0.1"
parking_lot = "0.11.1"
tp-timestamp = { version = "2.1.2", path = "../../../primitives/timestamp" }
derive_more = "0.99.2"
prometheus-endpoint = { version = "2.1.2", package = "prometheus-endpoint", path = "../../../utils/prometheus" }
