[package]
name = "tc-executor-wasmtime"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Defines a `WasmRuntime` that uses the Wasmtime JIT to execute."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.8"
scoped-tls = "1.0"
tetsy-wasm = "0.41.0"
codec = { package = "tetsy-scale-codec", version = "2.0.0" }
tc-executor-common = { version = "0.8.0", path = "../common" }
tp-wasm-interface = { version = "2.0.0", path = "../../../primitives/wasm-interface" }
tp-runtime-interface = { version = "2.0.0", path = "../../../primitives/runtime-interface" }
tp-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-allocator = { version = "2.0.0", path = "../../../primitives/allocator" }
wasmtime = "0.19"
pwasm-utils = "0.14.0"

[dev-dependencies]
assert_matches = "1.3.0"
