[package]
name = "externalities"
version = "2.1.2"
license = "Apache-2.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
description = "Tetcore externalities abstraction"
documentation = "https://docs.rs/externalities"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tetcore-storage = { version = "2.1.2", path = "../storage", default-features = false }
tetcore-std = { version = "2.1.2", path = "../std", default-features = false }
environ = { version = "1.1.3", default-features = false }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"environ/std",
	"tetcore-std/std",
	"tetcore-storage/std",
]
