[package]
name = "fabric-system-rpc-runtime-api"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "Runtime API definition required by System RPC extensions."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-api = { version = "2.0.2", default-features = false, path = "../../../../primitives/api" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }

[features]
default = ["std"]
std = [
	"tp-api/std",
	"codec/std",
]
