[package]
name = "tetcore-wasm-interface"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
description = "Types and traits for interfacing between the host and the wasm runtime."
documentation = "https://docs.rs/tetcore-wasm-interface"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
twasmi = { version = "0.6.2", optional = true }
impl-trait-for-tuples = "0.2.0"
tetcore-std = { version = "2.0.1", path = "../std", default-features = false }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }

[features]
default = [ "std" ]
std = [ "twasmi", "tetcore-std/std", "codec/std" ]
