[package]
name = "tp-wasm-interface"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Types and traits for interfacing between the host and the wasm runtime."
documentation = "https://docs.rs/tp-wasm-interface"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
twasmi = { version = "0.6.2", optional = true }
impl-trait-for-tuples = "0.2.0"
tp-std = { version = "2.0.0", path = "../std", default-features = false }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

[features]
default = [ "std" ]
std = [ "twasmi", "tp-std/std", "codec/std" ]
