[package]
name = "frame-benchmarking-cli"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "CLI for benchmarking FRAME"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
frame-benchmarking = { version = "2.0.0", path = "../../../frame/benchmarking" }
tc-core = { version = "2.0.0", path = "../../../primitives/core" }
sc-service = { version = "0.8.0", default-features = false, path = "../../../client/service" }
sc-cli = { version = "0.8.0", path = "../../../client/cli" }
sc-client-db = { version = "0.8.0", path = "../../../client/db" }
sc-executor = { version = "0.8.0", path = "../../../client/executor" }
tc-externalities = { version = "0.8.0", path = "../../../primitives/externalities" }
tc-keystore = { version = "0.8.0", path = "../../../primitives/keystore" }
tc-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tc-state-machine = { version = "0.8.0", path = "../../../primitives/state-machine" }
codec = { version = "2.0.0", package = "tetsy-scale-codec" }
structopt = "0.3.8"
chrono = "0.4"
serde = "1.0.116"
handlebars = "3.5.0"
Inflector = "0.11.4"

[features]
default = ["db"]
db = ["sc-client-db/with-kvdb-rocksdb", "sc-client-db/with-tetsy-db"]
