[package]
name = "tc-session"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Primitives for sessions"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-api = { version = "2.0.0", default-features = false, path = "../api" }
tc-core = { version = "2.0.0", default-features = false, path = "../core" }
tc-std = { version = "2.0.0", default-features = false, path = "../std" }
tc-staking = { version = "2.0.0", default-features = false, path = "../staking" }
tc-runtime = { version = "2.0.0", optional = true, path = "../runtime" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"tc-api/std",
	"tc-core/std",
	"tc-std/std",
	"tc-staking/std",
	"tc-runtime/std",
]
