[package]
name = "tp-session"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Primitives for sessions"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tp-api = { version = "2.0.0", default-features = false, path = "../api" }
tp-core = { version = "2.0.0", default-features = false, path = "../core" }
tp-std = { version = "2.0.0", default-features = false, path = "../std" }
tp-staking = { version = "2.0.0", default-features = false, path = "../staking" }
tp-runtime = { version = "2.0.0", optional = true, path = "../runtime" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"tp-api/std",
	"tp-core/std",
	"tp-std/std",
	"tp-staking/std",
	"tp-runtime/std",
]
