[package]
name = "pallet-randomness-collective-flip"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/pallet-randomness-collective-flip"
description = "FRAME randomness collective flip pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
safe-mix = { version = "1.0", default-features = false }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tp-runtime = { version = "2.0.2", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
tetcore-std = { version = "2.0.2", default-features = false, path = "../../primitives/std" }

[dev-dependencies]
tet-core = { version = "2.0.2", path = "../../primitives/core" }
tet-io = { version = "2.0.2", path = "../../primitives/io" }
serde = { version = "1.0.101" }

[features]
default = ["std"]
std = [
	"safe-mix/std",
	"frame-system/std",
	"codec/std",
	"frame-support/std",
	"tp-runtime/std",
	"tetcore-std/std",
]
