[package]
name = "sc-consensus-slots"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic slots-based utilities for consensus"
edition = "2018"
build = "build.rs"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0" }
sc-client-api = { version = "2.0.0", path = "../../api" }
tc-core = { version = "2.0.0", path = "../../../primitives/core" }
tc-trie = { version = "2.0.0", path = "../../../primitives/trie" }
tc-application-crypto = { version = "2.0.0", path = "../../../primitives/application-crypto" }
tc-arithmetic = { version = "2.0.0", path = "../../../primitives/arithmetic" }
tc-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tc-consensus-slots = { version = "0.8.0", path = "../../../primitives/consensus/slots" }
tc-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tc-state-machine = { version = "0.8.0", path = "../../../primitives/state-machine" }
tc-api = { version = "2.0.0", path = "../../../primitives/api" }
sc-telemetry = { version = "2.0.0", path = "../../telemetry" }
tc-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
tc-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
futures = "0.3.9"
futures-timer = "3.0.1"
parking_lot = "0.11.1"
log = "0.4.11"
thiserror = "1.0.21"

[dev-dependencies]
tetcore-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
