[package]
name = "pallet-democracy"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME pallet for democracy"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tp-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }

[dev-dependencies]
tp-core = { version = "2.0.0", path = "../../primitives/core" }
pallet-balances = { version = "2.0.0", path = "../balances" }
pallet-scheduler = { version = "2.0.0", path = "../scheduler" }
tp-storage = { version = "2.0.0", path = "../../primitives/storage" }
tetcore-test-utils = { version = "2.0.0", path = "../../test-utils" }
hex-literal = "0.3.1"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tetcore-std/std",
	"tp-io/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"tp-runtime/std",
	"frame-system/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"tp-runtime/runtime-benchmarks",
]
