[package]
name = "tp-runtime"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Runtime Modules shared primitive types."
documentation = "https://docs.rs/tp-runtime"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tp-core = { version = "2.0.0", default-features = false, path = "../core" }
tp-application-crypto = { version = "2.0.0", default-features = false, path = "../application-crypto" }
tp-arithmetic = { version = "2.0.0", default-features = false, path = "../arithmetic" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../std" }
tp-io = { version = "2.0.0", default-features = false, path = "../io" }
log = { version = "0.4.8", optional = true }
paste = "0.1.6"
rand = { version = "0.7.2", optional = true }
impl-trait-for-tuples = "0.2.0"
tetsy-util-mem = { version = "0.9.0", default-features = false, features = ["tetsy-primitive-types"] }
hash256-std-hasher = { version = "0.15.2", default-features = false }
either = { version = "1.5", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"
rand = "0.7.2"
tp-state-machine = { version = "0.8.0", path = "../state-machine" }

[features]
bench = []
runtime-benchmarks = []
default = ["std"]
std = [
	"tp-application-crypto/std",
	"tp-arithmetic/std",
	"codec/std",
	"log",
	"tp-core/std",
	"rand",
	"tetcore-std/std",
	"tp-io/std",
	"serde",
	"tetsy-util-mem/std",
	"hash256-std-hasher/std",
	"either/use_std",
]
