[package]
name = "tp-utils"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "I/O for Tetcore runtimes"
readme = "README.md"

[dependencies]
futures = "0.3.9"
futures-core = "0.3.4"
lazy_static = "1.4.0"
prometheus = { version = "0.10.0", default-features = false }
futures-timer = "3.0.2"

[features]
default = ["metered"]
metered = []
