[package]
name = "pallet-offences-benchmarking"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME offences pallet benchmarking"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../../benchmarking" }
frame-support = { version = "2.0.0", default-features = false, path = "../../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../system" }
pallet-babe = { version = "2.0.0", default-features = false, path = "../../babe" }
pallet-balances = { version = "2.0.0", default-features = false, path = "../../balances" }
pallet-grandpa = { version = "2.0.0", default-features = false, path = "../../grandpa" }
pallet-im-online = { version = "2.0.0", default-features = false, path = "../../im-online" }
pallet-offences = { version = "2.0.0", default-features = false, features = ["runtime-benchmarks"], path = "../../offences" }
pallet-session = { version = "2.0.0", default-features = false, path = "../../session" }
pallet-staking = { version = "2.0.0", default-features = false, features = ["runtime-benchmarks"], path = "../../staking" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
tp-staking = { version = "2.0.0", default-features = false, path = "../../../primitives/staking" }
tp-std = { version = "2.0.0", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
pallet-staking-reward-curve = { version = "2.0.0", path = "../../staking/reward-curve" }
pallet-timestamp = { version = "2.0.0", path = "../../timestamp" }
serde = { version = "1.0.101" }
tp-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-io = { version = "2.0.0", path = "../../../primitives/io" }

[features]
default = ["std"]
std = [
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-grandpa/std",
	"pallet-im-online/std",
	"pallet-offences/std",
	"pallet-session/std",
	"pallet-staking/std",
	"tp-runtime/std",
	"tp-staking/std",
	"tp-std/std",
	"codec/std",
]
