[package]
name = "noble-treasury"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/treasury"
description = "FABRIC noble to manage treasury"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.1.2", default-features = false, path = "../../primitives/std" }
tp-runtime = { version = "2.1.2", default-features = false, path = "../../primitives/runtime" }
fabric-support = { version = "2.1.2", default-features = false, path = "../support" }
fabric-system = { version = "2.1.2", default-features = false, path = "../system" }
noble-balances = { version = "2.1.2", default-features = false, path = "../balances" }
impl-trait-for-tuples = "0.2.0"

fabric-benchmarking = { version = "2.1.2", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
tet-io = { version = "2.1.2", path = "../../primitives/io" }
tet-core = { version = "2.1.2", path = "../../primitives/core" }
tetcore-storage = { version = "2.1.2", path = "../../primitives/storage" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tetcore-std/std",
	"tp-runtime/std",
	"fabric-support/std",
	"fabric-system/std",
	"noble-balances/std",
]
runtime-benchmarks = [
	"fabric-benchmarking",
	"fabric-support/runtime-benchmarks",
	"fabric-system/runtime-benchmarks",
]
