[package]
name = "tc-timestamp"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Tetcore core types and inherents for timestamps."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-api = { version = "2.0.0", default-features = false, path = "../api" }
tc-std = { version = "2.0.0", default-features = false, path = "../std" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../runtime" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-inherents = { version = "2.0.0", default-features = false, path = "../inherents" }
impl-trait-for-tuples = "0.2.0"
wasm-timer = { version = "0.2", optional = true }

[features]
default = [ "std" ]
std = [
	"tc-api/std",
	"tc-std/std",
	"tc-runtime/std",
	"codec/std",
	"tc-inherents/std",
	"wasm-timer",
]
