[package]
name = "tp-consensus-aura"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Primitives for Aura consensus"
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tp-consensus-aura"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tet-application-crypto = { version = "2.1.2", default-features = false, path = "../../application-crypto" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
tetcore-std = { version = "2.1.2", default-features = false, path = "../../std" }
tp-api = { version = "2.1.2", default-features = false, path = "../../api" }
tp-runtime = { version = "2.1.2", default-features = false, path = "../../runtime" }
tp-inherents = { version = "2.1.2", default-features = false, path = "../../inherents" }
tp-timestamp = { version = "2.1.2", default-features = false, path = "../../timestamp" }
tp-consensus-slots = { version = "2.1.2", default-features = false, path = "../slots" }

[features]
default = ["std"]
std = [
	"tet-application-crypto/std",
	"codec/std",
	"tetcore-std/std",
	"tp-api/std",
	"tp-runtime/std",
	"tp-inherents/std",
	"tp-timestamp/std",
]
