[package]
name = "tc-consensus-babe-rpc"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "RPC extensions for the BABE consensus algorithm"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-consensus-babe = { version = "2.1.2", path = "../" }
tc-rpc-api = { version = "2.1.2", path = "../../../rpc-api" }
tetsy-jsonrpc-core = "15.1.0"
tetsy-jsonrpc-core-client = "15.1.0"
tetsy-jsonrpc-derive = "15.1.0"
tp-consensus-babe = { version = "2.1.2", path = "../../../../primitives/consensus/babe" }
serde = { version = "1.0.104", features=["derive"] }
tp-blockchain = { version = "2.1.2", path = "../../../../primitives/blockchain" }
tp-runtime = { version = "2.1.2", path = "../../../../primitives/runtime" }
tc-consensus-epochs = { version = "2.1.2", path = "../../epochs" }
futures = { version = "0.3.4", features = ["compat"] }
derive_more = "0.99.2"
tp-api = { version = "2.1.2", path = "../../../../primitives/api" }
tp-consensus = { version = "2.1.2", path = "../../../../primitives/consensus/common" }
tet-core = { version = "2.1.2", path = "../../../../primitives/core" }
tet-application-crypto = { version = "2.1.2", path = "../../../../primitives/application-crypto" }
tp-keystore = { version = "2.1.2", path = "../../../../primitives/keystore" }

[dev-dependencies]
tc-consensus = { version = "2.1.2", path = "../../../consensus/common" }
serde_json = "1.0.50"
tp-keyring = { version = "2.1.2", path = "../../../../primitives/keyring" }
tc-keystore = { version = "2.1.2", path = "../../../keystore" }
tetcore-test-runtime-client = { path = "../../../../test-utils/runtime/client" }
tempfile = "3.1.0"
