[package]
name = "tp-consensus-vrf"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Primitives for VRF based consensus"
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/tetcoin/tetcore/"
homepage = "https://core.tetcoin.org"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { version = "2.0.1", package = "tetsy-scale-codec", default-features = false }
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated", "u64_backend"], default-features = false }
tetcore-std = { version = "2.0.0", path = "../../std", default-features = false }
tet-core = { version = "2.0.0", path = "../../core", default-features = false }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../runtime" }

[features]
default = ["std"]
std = [
	"codec/std",
	"schnorrkel/std",
	"tetcore-std/std",
	"tet-core/std",
	"tp-runtime/std",
]
