[package]
name = "tc-consensus-uncles"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Generic uncle inclusion utilities for consensus"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-client-api = { version = "2.0.0", path = "../../api" }
tp-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tp-authorship = { version = "2.0.0", path = "../../../primitives/authorship" }
tp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
tp-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
log = "0.4.8"
