[package]
name = "tetcore-test-runtime-client"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetcore Client testing utilities."
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
# publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-light = { version = "2.1.2", path = "../../../client/light" }
tp-consensus = { version = "2.1.2", path = "../../../primitives/consensus/common" }
tc-block-builder = { version = "2.1.2", path = "../../../client/block-builder" }
tetcore-test-client = { version = "2.1.2", path = "../../client" }
tet-core = { version = "2.1.2", path = "../../../primitives/core" }
tetcore-test-runtime = { version = "2.1.2", path = "../../runtime" }
tp-runtime = { version = "2.1.2", path = "../../../primitives/runtime" }
tp-api = { version = "2.1.2", path = "../../../primitives/api" }
tp-blockchain = { version = "2.1.2", path = "../../../primitives/blockchain" }
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
tc-client-api = { version = "2.1.2", path = "../../../client/api" }
tc-consensus = { version = "2.1.2", path = "../../../client/consensus/common" }
tc-service = { version = "2.1.2", default-features = false, path = "../../../client/service" }
futures = "0.3.9"
