[package]
name = "tetcore-test-runtime-client"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-light = { version = "2.0.0", path = "../../../client/light" }
tc-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
sc-block-builder = { version = "0.8.0", path = "../../../client/block-builder" }
tetcore-test-client = { version = "2.0.0", path = "../../client" }
tc-core = { version = "2.0.0", path = "../../../primitives/core" }
tetcore-test-runtime = { version = "2.0.0", path = "../../runtime" }
tc-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tc-api = { version = "2.0.0", path = "../../../primitives/api" }
tc-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
codec = { package = "tetsy-scale-codec", version = "2.0.0" }
sc-client-api = { version = "2.0.0", path = "../../../client/api" }
sc-consensus = { version = "0.8.0", path = "../../../client/consensus/common" }
sc-service = { version = "0.8.0", default-features = false, path = "../../../client/service" }
futures = "0.3.9"
