[package]
name = "pallet-society"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/pallet-society"
description = "FRAME society pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
rand_chacha = { version = "0.2", default-features = false }

[dev-dependencies]
tet-core = { version = "2.0.0", path = "../../primitives/core" }
tp-io ={ version = "2.0.0", path = "../../primitives/io" }
pallet-balances = { version = "2.0.0", path = "../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"serde",
	"tp-runtime/std",
	"rand_chacha/std",
	"tetcore-std/std",
	"frame-support/std",
	"frame-system/std",
]
runtime-benchmarks = [
	"tp-runtime/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
