[package]
name = "tp-sandbox"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tp-rpc"
description = "This crate provides means to instantiate and execute wasm modules."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
twasmi = { version = "0.6.2", optional = true }
tet-core = { version = "2.0.1", default-features = false, path = "../core" }
tetcore-std = { version = "2.0.1", default-features = false, path = "../std" }
tet-io = { version = "2.0.1", default-features = false, path = "../io" }
tetcore-wasm-interface = { version = "2.0.1", default-features = false, path = "../wasm-interface" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }

[dev-dependencies]
wat = "1.0"
assert_matches = "1.3.0"

[features]
default = ["std"]
std = [
	"twasmi",
	"tet-core/std",
	"tetcore-std/std",
	"codec/std",
	"tet-io/std",
	"tetcore-wasm-interface/std",
]
strict = []
