[package]
name = "tc-sandbox"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "This crate provides means to instantiate and execute wasm modules."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
wasmi = { version = "0.6.2", optional = true }
tc-core = { version = "2.0.0", default-features = false, path = "../core" }
tc-std = { version = "2.0.0", default-features = false, path = "../std" }
tc-io = { version = "2.0.0", default-features = false, path = "../io" }
tc-wasm-interface = { version = "2.0.0", default-features = false, path = "../wasm-interface" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }

[dev-dependencies]
wat = "1.0"
assert_matches = "1.3.0"

[features]
default = ["std"]
std = [
	"wasmi",
	"tc-core/std",
	"tc-std/std",
	"codec/std",
	"tc-io/std",
	"tc-wasm-interface/std",
]
strict = []
