[package]
name = "pallet-mmr"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME Merkle Mountain Range pallet."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
mmr-lib = { package = "ckb-merkle-mountain-range", default-features = false, version = "0.3.1" }
pallet-mmr-primitives = { version = "2.0.0", default-features = false, path = "./primitives" }
serde = { version = "1.0.101", optional = true }
tc-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tc-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }

[dev-dependencies]
env_logger = "0.5"
hex-literal = "0.3"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"mmr-lib/std",
	"pallet-mmr-primitives/std",
	"serde",
	"tc-core/std",
	"tc-io/std",
	"tc-runtime/std",
	"tc-std/std",
]
runtime-benchmarks = ["frame-benchmarking"]
