[package]
name = "tetkey"
version = "2.0.0"
description = "Tetkey utility, based on node_runtime."
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
documentation = "https://docs.rs/tetkey"
readme = "README.md"

[[bin]]
path = "src/main.rs"
name = "tetkey"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-cli = { version = "0.8.0", path = "../../../client/cli" }
structopt = "0.3.14"
