[package]
name = "tp-application-crypto"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
description = "Provides facilities for generating application specific crypto wrapper types."
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tp-application-crypto"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
tet-core = { version = "2.0.0", default-features = false, path = "../core" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
tetcore-std = { version = "2.0.0", default-features = false, path = "../std" }
tet-io = { version = "2.0.0", default-features = false, path = "../io" }

[features]
default = [ "std" ]
std = [ "full_crypto", "tet-core/std", "codec/std", "serde", "tetcore-std/std", "tet-io/std" ]

# This feature enables all crypto primitives for `no_std` builds like microcontrollers
# or Intel SGX.
# For the regular wasm runtime builds this should not be used.
full_crypto = [
	"tet-core/full_crypto",
	# Don't add `panic_handler` and `alloc_error_handler` since they are expected to be provided
	# by the user anyway.
	"tet-io/disable_panic_handler",
	"tet-io/disable_oom",
]
