[package]
name = "tc-executor-twasmi"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "This crate provides an implementation of `WasmRuntime` that is baked by twasmi."
documentation = "https://docs.rs/tc-executor-twasmi"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
log = "0.4.8"
twasmi = "0.6.2"
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
tc-executor-common = { version = "0.8.0", path = "../common" }
tetcore-wasm-interface = { version = "2.0.0", path = "../../../primitives/wasm-interface" }
tp-runtime-interface = { version = "2.0.0", path = "../../../primitives/runtime-interface" }
tet-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-allocator = { version = "2.0.0", path = "../../../primitives/allocator" }
