[package]
name = "pallet-transaction-payment"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME pallet to manage transaction payments"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
smallvec = "1.4.1"
tp-io = { version = "2.0.0", path = "../../primitives/io", default-features = false }
tp-core = { version = "2.0.0", path = "../../primitives/core", default-features = false }

[dev-dependencies]
serde_json = "1.0.41"
pallet-balances = { version = "2.0.0", path = "../balances" }
tp-storage = { version = "2.0.0", path = "../../primitives/storage" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tetcore-std/std",
	"tp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"tp-io/std",
	"tp-core/std",
]
