[package]
name = "noble-transaction-payment-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "RPC interface for the transaction payment module."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
tetsy-jsonrpc-core = "15.1.0"
tetsy-jsonrpc-core-client = "15.1.0"
tetsy-jsonrpc-derive = "15.1.0"
tet-core = { version = "2.0.2", path = "../../../primitives/core" }
tp-rpc = { version = "2.0.2", path = "../../../primitives/rpc" }
tp-runtime = { version = "2.0.2", path = "../../../primitives/runtime" }
tp-api = { version = "2.0.2", path = "../../../primitives/api" }
tp-blockchain = { version = "2.0.2", path = "../../../primitives/blockchain" }
noble-transaction-payment-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }
