[package]
name = "noble-indices"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/indices"
description = "FABRIC indices management noble"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tp-keyring = { version = "2.0.2", optional = true, path = "../../primitives/keyring" }
tetcore-std = { version = "2.0.2", default-features = false, path = "../../primitives/std" }
tet-io = { version = "2.0.2", default-features = false, path = "../../primitives/io" }
tp-runtime = { version = "2.0.2", default-features = false, path = "../../primitives/runtime" }
tet-core = { version = "2.0.2", default-features = false, path = "../../primitives/core" }
fabric-support = { version = "2.0.0", default-features = false, path = "../support" }
fabric-system = { version = "2.0.0", default-features = false, path = "../system" }

fabric-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
noble-balances = { version = "2.0.1", path = "../balances" }

[features]
default = ["std"]
std = [
	"serde",
	"tp-keyring",
	"codec/std",
	"tet-core/std",
	"tetcore-std/std",
	"tet-io/std",
	"fabric-support/std",
	"tp-runtime/std",
	"fabric-system/std",
]
runtime-benchmarks = [
	"fabric-benchmarking",
	"fabric-support/runtime-benchmarks",
]
