[package]
name = "tp-transaction-pool"
version = "2.0.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
description = "Transaction pool primitives types & Runtime API."
documentation = "https://docs.rs/tp-transaction-pool"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
thiserror = { version = "1.0.21", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", optional = true }
derive_more = { version = "0.99.11", optional = true }
futures = { version = "0.3.1", optional = true }
log = { version = "0.4.8", optional = true }
serde = { version = "1.0.101", features = ["derive"], optional = true}
tp-api = { version = "2.0.2", default-features = false, path = "../api" }
tp-blockchain = { version = "2.0.2", optional = true, path = "../blockchain" }
tp-runtime = { version = "2.0.2", default-features = false, path = "../runtime" }

[features]
default = [ "std" ]
std = [
	"codec",
	"derive_more",
	"futures",
	"log",
	"serde",
	"thiserror",
	"tp-api/std",
	"tp-blockchain",
	"tp-runtime/std",
]
