[package]
name = "sc-consensus-babe"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "BABE consensus algorithm for tetcore"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
documentation = "https://docs.rs/sc-consensus-babe"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", features = ["derive"] }
tc-consensus-babe = { version = "0.8.0", path = "../../../primitives/consensus/babe" }
tc-core = { version = "2.0.0", path = "../../../primitives/core" }
tc-application-crypto = { version = "2.0.0", path = "../../../primitives/application-crypto" }
tc-keystore = { version = "0.8.0", path = "../../../primitives/keystore" }
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.8"
serde = { version = "1.0.104", features = ["derive"] }
tc-version = { version = "2.0.0", path = "../../../primitives/version" }
tc-io = { version = "2.0.0", path = "../../../primitives/io" }
tc-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
tc-timestamp = { version = "2.0.0", path = "../../../primitives/timestamp" }
sc-telemetry = { version = "2.0.0", path = "../../telemetry" }
sc-keystore = { version = "2.0.0", path = "../../keystore" }
sc-client-api = { version = "2.0.0", path = "../../api" }
sc-consensus-epochs = { version = "0.8.0", path = "../epochs" }
tc-api = { version = "2.0.0", path = "../../../primitives/api" }
tc-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
tc-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tc-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
tc-consensus-slots = { version = "0.8.0", path = "../../../primitives/consensus/slots" }
tc-consensus-vrf = { version = "0.8.0", path = "../../../primitives/consensus/vrf" }
sc-consensus-uncles = { version = "0.8.0", path = "../uncles" }
sc-consensus-slots = { version = "0.8.0", path = "../slots" }
tc-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tc-utils = { version = "2.0.0", path = "../../../primitives/utils" }
fork-tree = { version = "2.0.0", path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "tetcore-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.8.0"}
futures = "0.3.9"
futures-timer = "3.0.1"
parking_lot = "0.11.1"
log = "0.4.8"
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated"] }
rand = "0.7.2"
merlin = "2.0"
pdqselect = "0.1.0"
derive_more = "0.99.2"
retain_mut = "0.1.2"

[dev-dependencies]
tc-keyring = { version = "2.0.0", path = "../../../primitives/keyring" }
tc-tracing = { version = "2.0.0", path = "../../../primitives/tracing" }
sc-executor = { version = "0.8.0", path = "../../executor" }
sc-network = { version = "0.8.0", path = "../../network" }
sc-network-test = { version = "0.8.0", path = "../../network/test" }
sc-service = { version = "0.8.0", default-features = false, path = "../../service" }
tetcore-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
sc-block-builder = { version = "0.8.0", path = "../../block-builder" }
rand_chacha = "0.2.2"
tempfile = "3.1.0"

[features]
test-helpers = []
