[package]
name = "tc-consensus-babe"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "BABE consensus algorithm for tetcore"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
documentation = "https://docs.rs/tc-consensus-babe"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", features = ["derive"] }
tp-consensus-babe = { version = "0.8.0", path = "../../../primitives/consensus/babe" }
tet-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-application-crypto = { version = "2.0.0", path = "../../../primitives/application-crypto" }
tp-keystore = { version = "0.8.0", path = "../../../primitives/keystore" }
num-bigint = "0.2.3"
num-rational = "0.2.2"
num-traits = "0.2.8"
serde = { version = "1.0.104", features = ["derive"] }
tp-version = { version = "2.0.0", path = "../../../primitives/version" }
tp-io = { version = "2.0.0", path = "../../../primitives/io" }
tp-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
tp-timestamp = { version = "2.0.0", path = "../../../primitives/timestamp" }
tc-telemetry = { version = "2.0.0", path = "../../telemetry" }
tc-keystore = { version = "2.0.0", path = "../../keystore" }
tc-client-api = { version = "2.0.0", path = "../../api" }
tc-consensus-epochs = { version = "0.8.0", path = "../epochs" }
tp-api = { version = "2.0.0", path = "../../../primitives/api" }
tp-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
tp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
tp-consensus-slots = { version = "0.8.0", path = "../../../primitives/consensus/slots" }
tp-consensus-vrf = { version = "0.8.0", path = "../../../primitives/consensus/vrf" }
tc-consensus-uncles = { version = "0.8.0", path = "../uncles" }
tc-consensus-slots = { version = "0.8.0", path = "../slots" }
tp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
tetcore-utils = { version = "2.0.0", path = "../../../primitives/utils" }
forktree = { version = "2.0.0", path = "../../../utils/forktree" }
prometheus-endpoint = { package = "prometheus-endpoint", path = "../../../utils/prometheus", version = "0.8.0"}
futures = "0.3.9"
futures-timer = "3.0.1"
parking_lot = "0.11.1"
log = "0.4.8"
schnorrkel = { version = "0.9.1", features = ["preaudit_deprecated"] }
rand = "0.7.2"
merlin = "2.0"
pdqselect = "0.1.0"
derive_more = "0.99.2"
retain_mut = "0.1.2"

[dev-dependencies]
tp-keyring = { version = "2.0.0", path = "../../../primitives/keyring" }
tetcore-tracing = { version = "2.0.0", path = "../../../primitives/tracing" }
tc-executor = { version = "0.8.0", path = "../../executor" }
tc-network = { version = "0.8.0", path = "../../network" }
tc-network-test = { version = "0.8.0", path = "../../network/test" }
tc-service = { version = "0.8.0", default-features = false, path = "../../service" }
tetcore-test-runtime-client = { version = "2.0.0", path = "../../../test-utils/runtime/client" }
tc-block-builder = { version = "0.8.0", path = "../../block-builder" }
rand_chacha = "0.2.2"
tempfile = "3.1.0"

[features]
test-helpers = []
