[package]
name = "pallet-authorship"
version = "2.0.1"
description = "Block and Uncle Author tracking for the FRAME"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-inherents = { version = "2.0.0", default-features = false, path = "../../primitives/inherents" }
tc-authorship = { version = "2.0.0", default-features = false, path = "../../primitives/authorship" }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
impl-trait-for-tuples = "0.2.0"

[dev-dependencies]
tc-core = { version = "2.0.0", path = "../../primitives/core" }
tc-io ={ version = "2.0.0", path = "../../primitives/io" }
serde = { version = "1.0.101" }

[features]
default = ["std"]
std = [
	"codec/std",
	"tc-inherents/std",
	"tc-runtime/std",
	"tc-std/std",
	"frame-support/std",
	"frame-system/std",
	"tc-authorship/std",
]
