[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Tetcore node implementation in Rust."
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-runtime = { version = "2.0.0", path = "../runtime" }
tc-executor = { version = "0.8.0", path = "../../../client/executor" }
tet-core = { version = "2.0.0", path = "../../../primitives/core" }
tp-keystore = { version = "0.8.0", path = "../../../primitives/keystore" }
tp-io = { version = "2.0.0", path = "../../../primitives/io" }
tp-state-machine = { version = "0.8.0", path = "../../../primitives/state-machine" }
tp-trie = { version = "2.0.0", path = "../../../primitives/trie" }
tetsy-trie-root = "0.16.0"
frame-benchmarking = { version = "2.0.0", path = "../../../frame/benchmarking" }

[dev-dependencies]
criterion = "0.3.0"
frame-support = { version = "2.0.0", path = "../../../frame/support" }
frame-system = { version = "2.0.0", path = "../../../frame/system" }
node-testing = { version = "2.0.0", path = "../testing" }
pallet-balances = { version = "2.0.0", path = "../../../frame/balances" }
pallet-contracts = { version = "2.0.0", path = "../../../frame/contracts" }
pallet-grandpa = { version = "2.0.0", path = "../../../frame/grandpa" }
pallet-im-online = { version = "2.0.0", path = "../../../frame/im-online" }
pallet-indices = { version = "2.0.0", path = "../../../frame/indices" }
pallet-session = { version = "2.0.0", path = "../../../frame/session" }
pallet-timestamp = { version = "2.0.0", path = "../../../frame/timestamp" }
pallet-transaction-payment = { version = "2.0.0", path = "../../../frame/transaction-payment" }
pallet-treasury = { version = "2.0.0", path = "../../../frame/treasury" }
tp-application-crypto = { version = "2.0.0", path = "../../../primitives/application-crypto" }
tp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
externalities = { version = "0.8.0", path = "../../../primitives/externalities" }
tetcore-test-client = { version = "2.0.0", path = "../../../test-utils/client" }
wat = "1.0"

[features]
wasmtime = [
	"tc-executor/wasmtime",
]
twasmi-errno = [
	"tc-executor/twasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
