[package]
name = "pallet-babe"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Consensus extension module for BABE consensus. Collects on-chain randomness from VRF outputs and manages epoch transitions."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
pallet-authorship = { version = "2.0.0", default-features = false, path = "../authorship" }
pallet-session = { version = "2.0.0", default-features = false, path = "../session" }
pallet-timestamp = { version = "2.0.0", default-features = false, path = "../timestamp" }
serde = { version = "1.0.101", optional = true }
tc-application-crypto = { version = "2.0.0", default-features = false, path = "../../primitives/application-crypto" }
tc-consensus-babe = { version = "0.8.0", default-features = false, path = "../../primitives/consensus/babe" }
tc-consensus-vrf = { version = "0.8.0", default-features = false, path = "../../primitives/consensus/vrf" }
tc-inherents = { version = "2.0.0", default-features = false, path = "../../primitives/inherents" }
tc-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tc-session = { version = "2.0.0", default-features = false, path = "../../primitives/session" }
tc-staking = { version = "2.0.0", default-features = false, path = "../../primitives/staking" }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tc-timestamp = { version = "2.0.0", default-features = false, path = "../../primitives/timestamp" }

[dev-dependencies]
frame-benchmarking = { version = "2.0.0", path = "../benchmarking" }
pallet-balances = { version = "2.0.0", path = "../balances" }
pallet-offences = { version = "2.0.0", path = "../offences" }
pallet-staking = { version = "2.0.0", path = "../staking" }
pallet-staking-reward-curve = { version = "2.0.0", path = "../staking/reward-curve" }
tc-core = { version = "2.0.0", path = "../../primitives/core" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-session/std",
	"pallet-timestamp/std",
	"serde",
	"tc-application-crypto/std",
	"tc-consensus-babe/std",
	"tc-consensus-vrf/std",
	"tc-inherents/std",
	"tc-io/std",
	"tc-runtime/std",
	"tc-session/std",
	"tc-staking/std",
	"tc-std/std",
	"tc-timestamp/std",
]
runtime-benchmarks = ["frame-benchmarking"]
