[package]
name = "tc-storage"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Storage related primitives"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
documentation = "https://docs.rs/tc-storage/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-std = { version = "2.0.0", default-features = false, path = "../std" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
impl-serde = { version = "0.3.1", optional = true }
ref-cast = "1.0.0"
tc-debug-derive = { version = "2.0.0", path = "../debug-derive" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }

[features]
default = [ "std" ]
std = [ "tc-std/std", "serde", "impl-serde", "codec/std" ]
