[package]
name = "pallet-authority-discovery"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME pallet for authority discovery"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-authority-discovery = { version = "2.0.0", default-features = false, path = "../../primitives/authority-discovery" }
tp-application-crypto = { version = "2.0.0", default-features = false, path = "../../primitives/application-crypto" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tp-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
serde = { version = "1.0.101", optional = true }
pallet-session = { version = "2.0.0", features = ["historical" ], path = "../session", default-features = false }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }

[dev-dependencies]
tp-core = { version = "2.0.0", path = "../../primitives/core" }
tp-io = { version = "2.0.0", path = "../../primitives/io" }
tp-staking = { version = "2.0.0", default-features = false, path = "../../primitives/staking" }

[features]
default = ["std"]
std = [
	"tp-application-crypto/std",
	"tp-authority-discovery/std",
	"codec/std",
	"tp-std/std",
	"serde",
	"pallet-session/std",
	"tp-runtime/std",
	"frame-support/std",
	"frame-system/std",
]
