[package]
name = "tp-consensus"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Common utilities for building and using consensus engines in tetcore."
documentation = "https://docs.rs/tp-consensus/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
thiserror = "1.0.21"
libp2p = { version = "0.34.0", default-features = false }
log = "0.4.8"
tp-core = { path= "../../core", version = "2.0.0"}
tp-inherents = { version = "2.0.0", path = "../../inherents" }
tp-state-machine = { version = "0.8.0", path = "../../state-machine" }
futures = { version = "0.3.1", features = ["thread-pool"] }
futures-timer = "3.0.1"
tp-std = { version = "2.0.0", path = "../../std" }
tp-version = { version = "2.0.0", path = "../../version" }
tp-runtime = { version = "2.0.0", path = "../../runtime" }
tp-utils = { version = "2.0.0", path = "../../utils" }
tp-trie = { version = "2.0.0", path = "../../trie" }
tp-api = { version = "2.0.0", path = "../../api" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", features = ["derive"] }
parking_lot = "0.11.1"
serde = { version = "1.0", features = ["derive"] }
prometheus-endpoint = { package = "tetcore-prometheus-endpoint", path = "../../../utils/prometheus", version = "0.8.0"}
wasm-timer = "0.2.5"

[dev-dependencies]
futures = "0.3.9"
tp-test-primitives = { version = "2.0.0", path = "../../test-primitives" }

[features]
default = []
