[package]
name = "noble-elections-phragmen"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/elections-phragmen"
description = "FABRIC noble based on seq-Phragmén election method."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
tp-runtime = { version = "2.1.2", default-features = false, path = "../../primitives/runtime" }
tp-npos-elections = { version = "2.1.2", default-features = false, path = "../../primitives/npos-elections" }
fabric-support = { version = "2.1.2", default-features = false, path = "../support" }
fabric-system = { version = "2.1.2", default-features = false, path = "../system" }
tetcore-std = { version = "2.1.2", default-features = false, path = "../../primitives/std" }
fabric-benchmarking = { version = "2.1.2", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
tet-io = { version = "2.1.2", path = "../../primitives/io" }
hex-literal = "0.3.1"
noble-balances = { version = "2.1.2", path = "../balances" }
tet-core = { version = "2.1.2", path = "../../primitives/core" }
tetcore-test-utils = { path = "../../test-utils" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"fabric-support/std",
	"tp-runtime/std",
	"tp-npos-elections/std",
	"fabric-system/std",
	"tetcore-std/std",
]
runtime-benchmarks = [
	"fabric-benchmarking",
	"fabric-support/runtime-benchmarks",
	"fabric-system/runtime-benchmarks",
]
