[package]
name = "tc-trie"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Patricia trie stuff using a tetsy-scale-codec node format"
repository = "https://github.com/tetcoin/tetcore/"
license = "Apache-2.0"
edition = "2018"
homepage = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tc-trie"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
name = "bench"
harness = false

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
tc-std = { version = "2.0.0", default-features = false, path = "../std" }
hash-db = { version = "0.15.2", default-features = false }
trie-db = { version = "0.22.2", default-features = false }
trie-root = { version = "0.16.0", default-features = false }
memory-db = { version = "0.26.0", default-features = false }
tc-core = { version = "2.0.0", default-features = false, path = "../core" }

[dev-dependencies]
trie-bench = "0.27.0"
trie-standardmap = "0.15.2"
criterion = "0.3.3"
hex-literal = "0.3.1"
tc-runtime = { version = "2.0.0", path = "../runtime" }

[features]
default = ["std"]
std = [
	"tc-std/std",
	"codec/std",
	"hash-db/std",
	"memory-db/std",
	"trie-db/std",
	"trie-root/std",
	"tc-core/std",
]
memory-tracker = []
