[package]
name = "tp-trie"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Patricia trie stuff using a tetsy-scale-codec node format"
repository = "https://github.com/tetcoin/tetcore/"
license = "Apache-2.0"
edition = "2018"
homepage = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tp-trie"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bench]]
name = "bench"
harness = false

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
tetcore-std = { version = "2.0.0", default-features = false, path = "../std" }
tetsy-hash-db = { version = "0.15.2", default-features = false }
tetsy-trie-db = { version = "0.22.2", default-features = false }
tetsy-trie-root = { version = "0.16.0", default-features = false }
tetsy-memory-db = { version = "0.26.0", default-features = false }
tet-core = { version = "2.0.0", default-features = false, path = "../core" }

[dev-dependencies]
trie-bench = "0.27.0"
trie-standardmap = "0.15.2"
criterion = "0.3.3"
hex-literal = "0.3.1"
tp-runtime = { version = "2.0.0", path = "../runtime" }

[features]
default = ["std"]
std = [
	"tetcore-std/std",
	"codec/std",
	"tetsy-hash-db/std",
	"tetsy-memory-db/std",
	"tetsy-trie-db/std",
	"tetsy-trie-root/std",
	"tet-core/std",
]
memory-tracker = []
