[package]
name = "tc-finality-grandpa"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Primitives for GRANDPA integration, suitable for WASM compilation."
documentation = "https://docs.rs/tc-finality-grandpa"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
grandpa = { package = "finality-grandpa", version = "0.13.0", default-features = false, features = ["derive-codec"] }
log = { version = "0.4.8", optional = true }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
tc-api = { version = "2.0.0", default-features = false, path = "../api" }
tc-application-crypto = { version = "2.0.0", default-features = false, path = "../application-crypto" }
tc-core = { version = "2.0.0", default-features = false, path = "../core" }
tc-keystore = { version = "0.8.0", default-features = false, path = "../keystore", optional = true }
tc-runtime = { version = "2.0.0", default-features = false, path = "../runtime" }
tc-std = { version = "2.0.0", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	"log",
	"serde",
	"codec/std",
	"grandpa/std",
	"tc-api/std",
	"tc-application-crypto/std",
	"tc-core/std",
	"tc-keystore",
	"tc-runtime/std",
	"tc-std/std",
]
