[package]
name = "tp-finality-grandpa"
version = "2.0.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
description = "Primitives for GRANDPA integration, suitable for WASM compilation."
documentation = "https://docs.rs/tp-finality-grandpa"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]


[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
grandpa = { package = "tetsy-finality-grandpa", version = "0.13.0", default-features = false, features = ["derive-codec"] }
log = { version = "0.4.8", optional = true }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
tp-api = { version = "2.1.2", default-features = false, path = "../api" }
tet-application-crypto = { version = "2.1.2", default-features = false, path = "../application-crypto" }
tet-core = { version = "2.1.2", default-features = false, path = "../core" }
tp-keystore = { version = "2.1.2", default-features = false, path = "../keystore", optional = true }
tp-runtime = { version = "2.1.2", default-features = false, path = "../runtime" }
tetcore-std = { version = "2.1.2", default-features = false, path = "../std" }

[features]
default = ["std"]
std = [
	"log",
	"serde",
	"codec/std",
	"grandpa/std",
	"tp-api/std",
	"tet-application-crypto/std",
	"tet-core/std",
	"tp-keystore",
	"tp-runtime/std",
	"tetcore-std/std",
]
