[package]
name = "noble-contracts-rpc-runtime-api"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore/"
description = "Runtime API definition required by Contracts RPC extensions."
readme = "README.md"
# publish = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-api = { version = "2.1.2", default-features = false, path = "../../../../primitives/api" }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.1.2", default-features = false, path = "../../../../primitives/std" }
tp-runtime = { version = "2.1.2", default-features = false, path = "../../../../primitives/runtime" }
noble-contracts-primitives = { version = "2.1.2", default-features = false, path = "../../common" }

[features]
default = ["std"]
std = [
	"tp-api/std",
	"codec/std",
	"tetcore-std/std",
	"tp-runtime/std",
	"noble-contracts-primitives/std",
]
