[package]
name = "tp-consensus-babe"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-application-crypto = { version = "2.0.0", default-features = false, path = "../../application-crypto" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
merlin = { version = "2.0", default-features = false }
tp-std = { version = "2.0.0", default-features = false, path = "../../std" }
tp-api = { version = "2.0.0", default-features = false, path = "../../api" }
tp-consensus = { version = "0.8.0", optional = true, path = "../common" }
tp-consensus-slots = { version = "0.8.0", default-features = false, path = "../slots" }
tp-consensus-vrf = { version = "0.8.0", path = "../vrf", default-features = false }
tp-core = { version = "2.0.0", default-features = false, path = "../../core" }
tp-inherents = { version = "2.0.0", default-features = false, path = "../../inherents" }
tp-keystore = { version = "0.8.0", default-features = false, path = "../../keystore", optional = true }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../runtime" }
tp-timestamp = { version = "2.0.0", default-features = false, path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"tp-application-crypto/std",
	"codec/std",
	"merlin/std",
	"tp-std/std",
	"tp-api/std",
	"tp-consensus",
	"tp-consensus-slots/std",
	"tp-consensus-vrf/std",
	"tp-core/std",
	"tp-inherents/std",
	"tp-keystore",
	"tp-runtime/std",
	"tp-timestamp/std",
]
