[package]
name = "tc-consensus-babe"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for BABE consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tc-application-crypto = { version = "2.0.0", default-features = false, path = "../../application-crypto" }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
merlin = { version = "2.0", default-features = false }
tc-std = { version = "2.0.0", default-features = false, path = "../../std" }
tc-api = { version = "2.0.0", default-features = false, path = "../../api" }
tc-consensus = { version = "0.8.0", optional = true, path = "../common" }
tc-consensus-slots = { version = "0.8.0", default-features = false, path = "../slots" }
tc-consensus-vrf = { version = "0.8.0", path = "../vrf", default-features = false }
tc-core = { version = "2.0.0", default-features = false, path = "../../core" }
tc-inherents = { version = "2.0.0", default-features = false, path = "../../inherents" }
tc-keystore = { version = "0.8.0", default-features = false, path = "../../keystore", optional = true }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../runtime" }
tc-timestamp = { version = "2.0.0", default-features = false, path = "../../timestamp" }

[features]
default = ["std"]
std = [
	"tc-application-crypto/std",
	"codec/std",
	"merlin/std",
	"tc-std/std",
	"tc-api/std",
	"tc-consensus",
	"tc-consensus-slots/std",
	"tc-consensus-vrf/std",
	"tc-core/std",
	"tc-inherents/std",
	"tc-keystore",
	"tc-runtime/std",
	"tc-timestamp/std",
]
