[package]
name = "pallet-balances"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/pallet-balances"
description = "FRAME pallet to manage balances"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }

[dev-dependencies]
tet-io = { version = "2.0.0", path = "../../primitives/io" }
tet-core = { version = "2.0.0", path = "../../primitives/core" }
pallet-transaction-payment = { version = "2.0.0", path = "../transaction-payment" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tetcore-std/std",
	"tp-runtime/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
]
runtime-benchmarks = ["frame-benchmarking"]
