[package]
name = "pallet-elections"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME pallet for elections"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
tc-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tc-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tc-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
tc-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }

[dev-dependencies]
hex-literal = "0.3.1"
pallet-balances = { version = "2.0.0", path = "../balances" }

[features]
default = ["std"]
std = [
	"codec/std",
	"tc-core/std",
	"tc-std/std",
	"serde",
	"tc-io/std",
	"frame-support/std",
	"tc-runtime/std",
	"frame-system/std",
]
