[package]
name = "tc-chain-spec"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Tetcore chain configurations types."
readme = "README.md"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
