[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-template'
version = "2.0.0"
license = "Unlicense"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME pallet template for defining custom runtime logic."
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }

[dev-dependencies]
serde = { version = "1.0.101" }

[dependencies.frame-support]
default-features = false
version = "2.0.0"
path = "../../../../frame/support"

[dependencies.frame-system]
default-features = false
version = "2.0.0"
path = "../../../../frame/system"

[dev-dependencies.tp-core]
default-features = false
version = "2.0.0"
path = "../../../../primitives/core"

[dev-dependencies.tp-io]
default-features = false
version = "2.0.0"
path = "../../../../primitives/io"

[dev-dependencies.tp-runtime]
default-features = false
version = "2.0.0"
path = "../../../../primitives/runtime"


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std'
]
