[package]
name = "pallet-session"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME sessions pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
tet-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
tp-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tp-session = { version = "2.0.0", default-features = false, path = "../../primitives/session" }
tp-staking = { version = "2.0.0", default-features = false, path = "../../primitives/staking" }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
pallet-timestamp = { version = "2.0.0", default-features = false, path = "../timestamp" }
tp-trie = { version = "2.0.0", optional = true, default-features = false, path = "../../primitives/trie" }
impl-trait-for-tuples = "0.1"

[dev-dependencies]
tp-application-crypto = { version = "2.0.0", path = "../../primitives/application-crypto" }
lazy_static = "1.4.0"

[features]
default = ["std", "historical"]
historical = ["tp-trie"]
std = [
	"serde",
	"codec/std",
	"tetcore-std/std",
	"tp-io/std",
	"frame-support/std",
	"tet-core/std",
	"tp-runtime/std",
	"tp-session/std",
	"tp-staking/std",
	"pallet-timestamp/std",
	"tp-trie/std",
]
