[package]
name = "tp-allocator"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Collection of allocator implementations."
documentation = "https://docs.rs/tp-allocator"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tp-std = { version = "2.0.0", path = "../std", default-features = false }
tp-core = { version = "2.0.0", path = "../core", default-features = false }
tp-wasm-interface = { version = "2.0.0", path = "../wasm-interface", default-features = false }
log = { version = "0.4.11", optional = true }
thiserror = { version = "1.0.21", optional = true }

[features]
default = [ "std" ]
std = [
	"tp-std/std",
	"tp-core/std",
	"tp-wasm-interface/std",
	"log",
	"thiserror",
]
