[package]
name = "tp-allocator"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/tp-allocator"
description = "Collection of allocator implementations."
documentation = "https://docs.rs/tp-allocator"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
tetcore-std = { version = "2.0.0", path = "../std", default-features = false }
tet-core = { version = "2.0.0", path = "../core", default-features = false }
tetcore-wasm-interface = { version = "2.0.0", path = "../wasm-interface", default-features = false }
log = { version = "0.4.11", optional = true }
thiserror = { version = "1.0.21", optional = true }

[features]
default = [ "std" ]
std = [
	"tetcore-std/std",
	"tet-core/std",
	"tetcore-wasm-interface/std",
	"log",
	"thiserror",
]
