[package]
name = "tc-consensus-epochs"
version = "0.8.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
description = "Generic epochs-based utilities for consensus"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", features = ["derive"] }
parking_lot = "0.11.1"
forktree = { version = "2.0.0", path = "../../../utils/forktree" }
tp-runtime = {  path = "../../../primitives/runtime" , version = "2.0.0"}
tp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
tc-client-api = { path = "../../api" , version = "2.0.0"}
