[package]
name = "pallet-mmr-primitives"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "FRAME Merkle Mountain Range primitives."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false, path = "../../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../../system" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
tp-api = { version = "2.0.0", default-features = false, path = "../../../primitives/api" }
tp-core = { version = "2.0.0", default-features = false, path = "../../../primitives/core" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../../primitives/runtime" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../../primitives/std" }

[dev-dependencies]
hex-literal = "0.3"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"tp-api/std",
	"tp-core/std",
	"tp-runtime/std",
	"tetcore-std/std",
]
