[package]
name = "tp-database"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/tetcoin/tetcore"
repository = "https://github.com/tetcoin/tetcore/"
description = "Tetcore database trait."
documentation = "https://docs.rs/tp-database"
readme = "README.md"

[dependencies]
parking_lot = "0.11.1"
kvdb = "0.9.0"
