[package]
name = "noble-example"
version = "2.1.2"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Unlicense"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/noble-example"
description = "FABRIC example noble"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
fabric-support = { version = "2.1.2", default-features = false, path = "../support" }
fabric-system = { version = "2.1.2", default-features = false, path = "../system" }
noble-balances = { version = "2.1.2", default-features = false, path = "../balances" }
tp-runtime = { version = "2.1.2", default-features = false, path = "../../primitives/runtime" }
tetcore-std = { version = "2.1.2", default-features = false, path = "../../primitives/std" }
tet-io = { version = "2.1.2", default-features = false, path = "../../primitives/io" }

fabric-benchmarking = { version = "2.1.2", default-features = false, path = "../benchmarking", optional = true }

[dev-dependencies]
tet-core = { version = "2.1.2", path = "../../primitives/core", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"tp-runtime/std",
	"fabric-benchmarking/std",
	"fabric-support/std",
	"fabric-system/std",
	"noble-balances/std",
	"tet-io/std",
	"tetcore-std/std"
]
runtime-benchmarks = ["fabric-benchmarking"]
