[package]
name = "pallet-example-offchain-worker"
version = "2.0.1"
authors = ["Parity Technologies <admin@parity.io>", "Tetcoin Developers <support@tetcoin.org>"]
edition = "2018"
license = "Unlicense"
keywords = ["tetcoin", "tetcore", "crypto", "blockchain", "framework"]
categories = ["cryptography::cryptocurrencies"]
homepage = "https://core.tetcoin.org"
repository = "https://github.com/tetcoin/tetcore"
documentation = "https://docs.rs/pallet-example-offchain-worker"
description = "FRAME example pallet for offchain worker"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "tetsy-scale-codec", version = "2.0.1", default-features = false }
frame-support = { version = "2.0.0", default-features = false, path = "../support" }
frame-system = { version = "2.0.0", default-features = false, path = "../system" }
serde = { version = "1.0.101", optional = true }
tet-core = { version = "2.0.0", default-features = false, path = "../../primitives/core" }
tp-keystore = { version = "0.8.0", path = "../../primitives/keystore", optional = true }
tp-io = { version = "2.0.0", default-features = false, path = "../../primitives/io" }
tp-runtime = { version = "2.0.0", default-features = false, path = "../../primitives/runtime" }
tetcore-std = { version = "2.0.0", default-features = false, path = "../../primitives/std" }
lite-json = { version = "0.1", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"serde",
	"lite-json/std",
	"tet-core/std",
	"tp-io/std",
	"tp-keystore",
	"tp-runtime/std",
	"tetcore-std/std",
]
